# Generated by Django 3.1.5 on 2021-02-01 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0006_auto_20210201_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='borrower',
        ),
        migrations.AddField(
            model_name='course',
            name='borrower',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
