# Generated by Django 3.1.5 on 2021-02-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pages',
            field=models.ManyToManyField(blank=True, null=True, related_name='page', to='catalog.Page'),
        ),
    ]
