# Generated by Django 3.1.5 on 2021-02-04 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_course_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='pages',
        ),
        migrations.AddField(
            model_name='page',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='catalog.course'),
        ),
    ]
