# Generated by Django 3.1.5 on 2021-02-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AlterField(
            model_name='profile',
            name='progress',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
