# Generated by Django 3.1.5 on 2021-02-05 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20210205_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
