# Generated by Django 3.1.5 on 2021-02-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20210205_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='summary2',
            field=models.TextField(blank=True, help_text='Enter a brief description of the book', max_length=1000),
        ),
        migrations.AddField(
            model_name='course',
            name='summary3',
            field=models.TextField(blank=True, help_text='Enter a brief description of the book', max_length=1000),
        ),
    ]
